#21 Add basic ship health and reparation
ardliath/DeepSpace pull request #26
Opened 2018-10-01 21:12 UTC by JonPaternain

Hi,

I tried to add basic health and shielding to the ship entity, feel free to reject this PR if it differs from your original thoughts. 

Any criticism and improvements are welcome and greatly appreciated.

Thank you 🥇

2018-10-02 05:25 UTC, ardliath commented
This is amazing, you’ve saved me so much work - thank you!!!

I’ll go through the changes, I can see a few tweaks but generally it’s fantastic!

2018-10-02 09:49 UTC, ardliath requested changes
Really appreciate your help, you've got some great ideas here! Thanks for your contribution

2018-10-02 09:49 UTC, ardliath commented on DeepSpace.Contracts/IShieldUpgrades.cs
> +        float Weight { get; set; }
These should probably be doubles for consistency

2018-10-02 09:49 UTC, ardliath commented on DeepSpace.Contracts/IShieldUpgrades.cs
> +    public interface IShieldUpgrades
I really like the idea of shield upgrades - I hadn't thought about that!

2018-10-02 09:49 UTC, ardliath commented on DeepSpace/Controllers/ShipController.cs
> +        [ActionName("Repair")]
Can we make these posts with the signature /api/ship/repair/hull and /api/ship/repair/shields?

2018-10-02 09:49 UTC, ardliath commented on DeepSpace/Messages/RepairShipRequest.cs
> +        public double Health { get; set; }
As this is a UIless game players/developers will call this method directly. By giving them a health variable you're effectively asking them how much they'd like to heal. I'd much rather this heals by... let's say 10 points per call for the time being. That means a player needs to sit and repair for a little while before they can fight again

2018-10-02 09:49 UTC, ardliath commented on DeepSpace.Contracts/Ship.cs
> +        public void AddShieldUpgrade(IShieldUpgrades upgrade)
This class is saved directly into the database so it should just be a list of properties. Can you add these methods into ShipManager - that's where the BLL wants to live

2018-10-03 20:53 UTC, JonPaternain commented
Nice review, I'll work on it tomorrow if I have some spare time. Thanks! :)

2018-10-04 20:02 UTC, ardliath approved these changes

2018-10-04 20:03 UTC, ardliath commented
This looks fantastic, I’m just waiting for the CI checks to run and I’ll merge in

Thanks for your help!

2018-10-04 20:18 UTC, merged